Use Renode latest portable package
antmicro/tensorflow-arduino-examples pull request #28
Opened 2021-01-17 18:03 UTC by wojciechowskidawid

2021-01-18 08:53 UTC, PiotrZierhoffer requested changes
otherwise ok

2021-01-18 08:53 UTC, PiotrZierhoffer commented on examples/magic-wand/magic_wand.py
> +!mkdir -p renode && cd renode && wget https://dl.antmicro.com/projects/renode/builds/renode-latest.linux-portable.tar.gz && tar -xzf renode-latest.linux-portable.tar.gz --strip 1
make paths to repl etc relative

2021-01-18 08:53 UTC, PiotrZierhoffer commented on examples/magic-wand/magic_wand.py
> +!mkdir -p renode && cd renode && wget https://dl.antmicro.com/projects/renode/builds/renode-latest.linux-portable.tar.gz && tar -xzf renode-latest.linux-portable.tar.gz --strip 1
see https://github.com/antmicro/tensorflow-arduino-examples/issues/23

2021-01-20 16:13 UTC, mateusz-holenko approved these changes

2021-01-20 16:13 UTC, merged