Hello world
antmicro/tensorflow-arduino-examples pull request #39
Opened 2021-01-28 12:49 UTC by wojciechowskidawid

2021-01-28 18:06 UTC, PiotrZierhoffer requested changes
Minor suggestions, otherwise lgtm

2021-01-28 18:06 UTC, PiotrZierhoffer commented on examples/hello-world/hello_world.robot
> +    Execute Command           machine EnableProfiler "${CURDIR}/hello_world.dump"
we should actually use the `@` notation, just like in LoadELF, whenever we provide a path. You can change that in other robot files as well, maybe just a PR to verify the tests and merge without a review

2021-01-28 18:06 UTC, PiotrZierhoffer commented on examples/hello-world/hello_world.py
> +tell_renode('machine EnableProfiler "metrics.dump"')
`@` here as well (see the note in .robot file)

2021-01-28 18:06 UTC, PiotrZierhoffer commented on examples/hello-world/hello_world.py
> +"""## Run a hello-world example in Renode"""
the hello-world

2021-01-29 13:39 UTC, PiotrZierhoffer approved these changes
Fix this one thing and merge

2021-01-29 13:39 UTC, PiotrZierhoffer commented on examples/hello-world/hello_world.py
> +tell_renode('machine EnableProfiler "metrics.dump"')
This is not resolved

2021-01-29 14:04 UTC, mateusz-holenko approved these changes

2021-01-29 14:51 UTC, merged